apiVersion: apps/v1
kind: Deployment
metadata:
  name: emoji-typer
spec:
  selector:
    matchLabels:
      app: emoji-typer
  replicas: 5
  template:
    metadata:
      labels:
        app: emoji-typer
    spec:
      containers:
        - name: emoji-typer
          image: matisiekpl/emoji-typer
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: emoji-typer
spec:
  selector:
    app: emoji-typer
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30123
      targetPort: 3000
      port: 30123