// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "e8ad54d574961e8fa5f52e380e654a7b"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"d6469c13c8c86b6885d49e438465d0ef": "1f8b08000000000000ff84924fced33010c5f73985315bbecf745bd9969010274062edc4031ef09f608f5bdac81b369c01719df65ec84d222458b0893499f16fde7bb67414bc1ea40363f5c01863320019164d00c54f08e73965e26c4a912092e267b4e49485134ef0f4285e318c4868fc53998c0775787ecd37142179d0ef52ae418ab518a45877c931d94bdf7cd807dc410fb2cc26ea0f70bdfdbc7f3fb26571a95017d39a148f9e1cb3583f83fc98726066224c517181b140d71a805cb28acfa9d0ae04e35c89d16506c509be11df1c9a4a2e65ce666f2670c95bc88abfa9d4ff65f85a3183fd0f628be62fc6fb0cf75fb71fec4b0a10c9e4abf9073856a2143762a96340e2fa6db2e6f39f532fa458c77a70ddae1e64f52b60595e82991c0b508af904a5b595eb51b3652187e579b5d71a3b67248278dc1b9be89eaac71d273aaeb5418abe428aed86c4e38dfc0e0000ffff518230a02a020000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("Templates", "./templates")
		b.SetResolver("index.html", packr.Pointer{ForwardBox: gk, ForwardPath: "d6469c13c8c86b6885d49e438465d0ef"})
	}()
	return nil
}()
